<from method='POST' action='index.php'>
    <fieldset>
        <label for="password">Email</label>
        <input type="email" name="useremail"/>
    </fieldset>
    <fieldset>
        <label for="password"></label>
        <input type="password" name="userpassword"/>
    </fieldset>
    <fieldset class='sr-only'>
        <label for="formName"></label>
        <input type="text" name="formName"/>
    </fieldset>
    <fieldset>
        <button>Se connecter</button>
    </fieldset>
</from>